kind: pipeline
name: backend

steps:
  - name: test backend
    image: golang:1.12-stretch
    commands:
      - apt-get update && apt-get install -y git
      - go test ./...
  - name: publish-latest
    image: plugins/docker
    when:
      event: push
      branch: master
    settings:
      repo: containers.jasonraimondi.com/kim/ux-image-archive-api
      registry: containers.jasonraimondi.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: [ "latest" ]
      force_tag: true
      custom_dns: [ 10.0.0.1, 1.1.1.1 ]
---
kind: pipeline
name: frontend

steps:
  - name: test frontend
    image: node:alpine
    commands:
      - cd web
      - npm install
      - npm run build
  - name: publish-latest
    image: plugins/docker
    when:
      event: push
      branch: master
    settings:
      repo: containers.jasonraimondi.com/kim/ux-image-archive-ssr
      registry: containers.jasonraimondi.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: [ "latest" ]
      force_tag: true
      custom_dns: [ 10.0.0.1, 1.1.1.1 ]