version: "3.7"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: print
      POSTGRES_USER: print
      POSTGRES_PASSWORD: print
    ports:
      - 5432:5432
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: ["server", "/data"]
    ports:
      - 9000:9000
    volumes:
      - minio-config:/root/.minio
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: miniominiominio
      MINIO_SECRET_KEY: miniominiominio
      MINIO_HTTP_TRACE: /dev/stdout
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host: localhost; PathPrefixStrip: /media"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  minio-data:
  minio-config: