version: "3.7"

services:
  postgres:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: print
      POSTGRES_USER: print
      POSTGRES_PASSWORD: print
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: ["server", "/data"]
    ports:
      - 9000:9000
    volumes:
      - minio-config:/root/.minio
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: miniominiominio
      MINIO_SECRET_KEY: miniominiominio
      MINIO_HTTP_TRACE: /dev/stdout

volumes:
  postgres-data:
  minio-data:
  minio-config: