version: "3.7"

services:
  traefik:
    image: traefik
    command:
      - --configfile=/etc/traefik/config/traefik.toml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  web:
    build: ./web
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host: localhost"

  app:
    build: .
    environment:
      DB_CONNECTION: host=postgres port=5432 user=print password=print dbname=print sslmode=disable
    labels:
      - "traefik.enable=true"
      - "traefik.port=1323"
      - "traefik.frontend.rule=Host: localhost; PathPrefixStrip: /api"
